<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>2.0.0</Version>
    <Copyright>Copyright © 2022 Light Conversion, UAB</Copyright>
    <Description>Library for reliably storing and loading application settings/data to JSON file.</Description>
    <Authors>Light Conversion, Tevux Technologies</Authors>
    <Company>Light Conversion</Company>
    <RepositoryUrl>https://github.com/light-conversion/LightConversion-Storage-Settings</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="4.7.15" />
    <PackageReference Include="Tevux.Tools.RepositorySettings" Version="0.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Utf8Json" Version="1.3.7" />
  </ItemGroup>

  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>settings;reliable;file;c#;json</PackageTags>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>
</Project>
