<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Copyright>Copyright © 2022 Light Conversion, UAB</Copyright>
    <Description>Library for reliably storing and loading application settings/data to json file.</Description>
    <Authors>Light Conversion</Authors>
    <Company>Light Conversion</Company>
    <RepositoryUrl>https://github.com/light-conversion/LightConversion-Storage-Settings</RepositoryUrl>
    <RepositoryType></RepositoryType>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="4.4.11" />
    <PackageReference Include="Utf8Json" Version="1.3.7" />
  </ItemGroup>
  
  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
